eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    password: springstudent
    username: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver